# Generated by Django 3.1.5 on 2023-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login_tb',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
