# Generated by Django 3.1.5 on 2023-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0002_admin_login_tb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='cars')),
                ('name', models.CharField(default='', max_length=300)),
                ('people', models.CharField(default='', max_length=300)),
                ('fuel', models.CharField(default='', max_length=300)),
                ('miles', models.CharField(default='', max_length=300)),
                ('transmission', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
