# Generated by Django 3.1.5 on 2023-08-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0004_conatct_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='conatct_tb',
        ),
    ]
